[project]
name = "hikvision"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "openpyxl>=3.1.5",
    "plotly>=6.4.0",
    "seaborn>=0.13.2",
    "streamlit>=1.51.0",
]
